<?php
/**
 * @var $this Aoe_Profiler_Block_Adminhtml_Profiler_View
 */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head"><?php echo Mage::helper('aoe_scheduler')->__('Run details') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
            <?php echo $this->getChildHtml('aoe_profiler_filter') ?>
        </td>
    </tr>
</table>
</div>
<div>
    <?php echo $this->getChildHtml('aoe_profiler_tree') ?>
</div>
